codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: auto
        threshold: 1%
        # Allow coverage to drop by 1% before failing
        informational: false

    patch:
      default:
        target: 70%
        # New code should have at least 70% coverage
        informational: false

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false

ignore:
  - "tests/"
  - "benches/"
  - "examples/"
  - "**/*_test.rs"
  - "**/*_tests.rs"
  - "**/test_*.rs"
  - "src/bin/"
  # Ignore binaries as they're mostly entry points

flags:
  default:
    carryforward: true
