name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature. Please provide as much detail as possible to help us understand your request.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Describe the problem or limitation you're experiencing that this feature would solve.
      placeholder: I'm frustrated when... / It would be helpful to...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
      placeholder: I would like the application to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.
      placeholder: I've also thought about...

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe how you would use this feature and what benefits it would provide.
      placeholder: This feature would allow me to...
    validations:
      required: true

  - type: dropdown
    id: interface
    attributes:
      label: Interface
      description: Which interface would this feature apply to?
      options:
        - GUI
        - TUI
        - Both
        - CLI
        - Not applicable
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, mockups, screenshots, or examples about the feature request here.
